ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'FIRST_PURCHASE_DISCOUNT';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ORDER_COMPLETED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ORDER_CANCELLED';
